### ISSUE TITLE
OnSearchItemSelected is not Public. Cannot be accessed from Outside Package.

### ISSUE THREAD

**Issue by RationalRank** [ajithvgiri/Search-Dialog#1]
`OnSearchItemSelected` cannot be accessed. The issue might be with `OnSearchItemSelected` interface's Access Modifier.

**Comment by dzulfikar68** [comment]
implementation 'com.github.ajithvgiri:SearchDialog:v1.0' => in this still use (not public), please help me ....

**Comment by ajithvgiri** [comment]
@dzulfikar68  fixed
